# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Projects/fusion2_HWaccel_IP/rgb_gauss_sobel_full_64/vivado_ip_prj/constraints.xdc

# Block Designs: C:/Projects/fusion2_HWaccel_IP/rgb_gauss_sobel_full_64/vivado_ip_prj/src/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: C:/Projects/fusion2_HWaccel_IP/rgb_gauss_sobel_full_64/vivado_ip_prj/src/design_1/ip/design_1_blink_0_0/design_1_blink_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blink_0_0 || ORIG_REF_NAME==design_1_blink_0_0} -quiet] -quiet

# IP: C:/Projects/fusion2_HWaccel_IP/rgb_gauss_sobel_full_64/vivado_ip_prj/src/design_1/ip/design_1_cameras_wrapper_0_0/design_1_cameras_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_cameras_wrapper_0_0 || ORIG_REF_NAME==design_1_cameras_wrapper_0_0} -quiet] -quiet

# IP: C:/Projects/fusion2_HWaccel_IP/rgb_gauss_sobel_full_64/vivado_ip_prj/src/design_1/ip/design_1_fifo_generator_0_0/design_1_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_fifo_generator_0_0 || ORIG_REF_NAME==design_1_fifo_generator_0_0} -quiet] -quiet

# IP: C:/Projects/fusion2_HWaccel_IP/rgb_gauss_sobel_full_64/vivado_ip_prj/src/design_1/ip/design_1_line_buffer_0_0/design_1_line_buffer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_line_buffer_0_0 || ORIG_REF_NAME==design_1_line_buffer_0_0} -quiet] -quiet

# IP: C:/Projects/fusion2_HWaccel_IP/rgb_gauss_sobel_full_64/vivado_ip_prj/src/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: C:/Projects/fusion2_HWaccel_IP/rgb_gauss_sobel_full_64/vivado_ip_prj/src/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: C:/Projects/fusion2_HWaccel_IP/rgb_gauss_sobel_full_64/vivado_ip_prj/src/design_1/ip/design_1_ps7_0_axi_periph_0/design_1_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: C:/Projects/fusion2_HWaccel_IP/rgb_gauss_sobel_full_64/vivado_ip_prj/src/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_1 || ORIG_REF_NAME==design_1_auto_pc_1} -quiet] -quiet

# IP: C:/Projects/fusion2_HWaccel_IP/rgb_gauss_sobel_full_64/vivado_ip_prj/src/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: C:/Projects/fusion2_HWaccel_IP/rgb_gauss_sobel_full_64/vivado_ip_prj/src/design_1/ip/design_1_Subsystem_ip_0_0/design_1_Subsystem_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Subsystem_ip_0_0 || ORIG_REF_NAME==design_1_Subsystem_ip_0_0} -quiet] -quiet

# XDC: c:/Projects/fusion2_HWaccel_IP/rgb_gauss_sobel_full_64/vivado_ip_prj/src/design_1/ip/design_1_fifo_generator_0_0/design_1_fifo_generator_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_fifo_generator_0_0 || ORIG_REF_NAME==design_1_fifo_generator_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Projects/fusion2_HWaccel_IP/rgb_gauss_sobel_full_64/vivado_ip_prj/src/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Projects/fusion2_HWaccel_IP/rgb_gauss_sobel_full_64/vivado_ip_prj/src/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1_ooc.xdc

# XDC: c:/Projects/fusion2_HWaccel_IP/rgb_gauss_sobel_full_64/vivado_ip_prj/src/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc

# XDC: C:/Projects/fusion2_HWaccel_IP/rgb_gauss_sobel_full_64/vivado_ip_prj/src/design_1/design_1_ooc.xdc
